### ISSUE TITLE
Incompatibility with Windows 64bit.

### ISSUE THREAD

**Issue by rondoor** [slartibardfast/punkgraphicstream#2]
Is there any chance to fix this?
Or is it never to be updated anymore?

**Comment by slartibardfast** [comment]
hi, if you install a 32-bit JVM, it works fine with 64-bit windows. these can co-exist without issue.

I'm planning on doing an updated release with a bundled openjdk, 
both windows amd64 and macos soon.

**Comment by rondoor** [comment]
In my environment, Punkgraphicstream doesn't work with a 32bit JVM in my 64bit Win10. And I have no 64bit JVM installed.
I wish the bundled version will come in the future.

**Comment by slartibardfast** [comment]
hi @rondoor, I am preparing a 1.0.0 release for some time this month. 

in the mean time, a Java 8 JVM for windows 32 should work fine
